### ISSUE TITLE
renv_retrieve_incompatible

### ISSUE THREAD

**Issue by nick-youngblut** [aruaud/endoR#1]
It appears that endoR cannot be installed via `renv` for some reason:

```
> renv::install('aruaud/endoR')
Retrieving 'https://api.github.com/repos/aruaud/endoR/tarball/696fe3c25ddabc3bd4ee74378b1dd914105d91e4' ...
	OK [downloaded 781.2 Kb in 0.5 secs]
Error in state$requirements[[record$Package]] :
  wrong arguments for subsetting an environment
Traceback (most recent calls last):
11: renv::install("aruaud/endoR")
10: retrieve(names(remotes))
 9: handler(package, renv_retrieve_impl(package))
 8: renv_retrieve_impl(package)
 7: renv_retrieve_github(record)
 6: renv_retrieve_package(record, url, path)
 5: renv_retrieve_successful(record, path)
 4: retrieve(package)
 3: handler(package, renv_retrieve_impl(package))
 2: renv_retrieve_impl(package)
 1: renv_retrieve_incompatible(record)
```

The issue might be similar to https://github.com/rstudio/renv/issues/955

It could also have to do with the R version that I'm using: 4.1.2 (2021-11-01)

**Comment by nick-youngblut** [comment]
Adding a `sessionInfo()` at the end of your vignettes (eg., [titanic_bootstraps](https://github.com/aruaud/endoR/blob/main/vignettes/titanic_bootstraps.ipynb)) would be helpful to assessing which R & package versions that you successfully used

**Comment by aruaud** [comment]
Thanks Nick, I added documentation to the README file :)
