### ISSUE TITLE
`model2DE_resampling`

### ISSUE THREAD

**Issue by liamfitzstevens** [aruaud/endoR#7]
Bringing endoR to a new lab - hoping to expand its reach!

I train a model with caret ...
```
rf_model <- train(
  target ~ .,
  data = train_data,
  method = "rf",
  trControl = control,
  importance = TRUE
)

# note that I'd run colnames(df) <- compatibleNames(colnames(df)) earlier
```

... extracted the final model (since it's caret; this is the same format now as had I used the randomForest package) and ran `model2DE_resampling` ...
```
rf_final_model <- rf_model$finalModel
stability_results <- model2DE_resampling(
  model = rf_final_model,
  data = tmp,
  target = tmp$target,
  model_type = "rf")
```

... which yields the following error. Do you know what might be wrong? 
```
Extract rules...
Discretise data
Discretise rules
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
```

Thank you and hi from St. Louis!!

**Comment by liamfitzstevens** [comment]
P.S. the same without resampling also pops an error
```
rf_final_model <- rf_model$finalModel
stability_results <- model2DE(
  model = rf_final_model,
  data = tmp,
  target = tmp$target,
  model_type = "rf")
  ```
```
Extract rules...
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
```

**Comment by liamfitzstevens** [comment]
### **Update**
The code above runs error-free when factor features are removed (leaving only numerical features). This is the case for both RF regressions and classifiers.

If I switch from `caret::train` to `ranger::ranger`, factor features work. Do you know why this is?

Is there a way I can keep using `caret::train`, or do I need to switch to `ranger::ranger`?

**Comment by aruaud** [comment]
Hi @liamfitzstevens - I think the issue comes from the fact that the `caret` package changes multi-class variables to dummy ones (0-1 encoded for each level of the original variable). Such that, when you feed the original variables to endoR, the trees don't correspond and are "out of bound". You need to feed endoR with the caret-dummified data. 

```
data_car <- model.matrix(target ~ ., data = tmp)
stability_results <- model2DE(
  model = rf_final_model,
  data = data_car,
  target = tmp$target,
  classPos = tmp$target[1],
  model_type = "rf")
```
